# Generated by Django 4.2.3 on 2023-07-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photography_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Imagem'),
        ),
    ]
