# Generated by Django 4.2.3 on 2023-07-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('NEBULA', 'Nebulosa'), ('GALAXY', 'Galáxia'), ('PLANET', 'Planeta'), ('STAR', 'Estrela')], default='', max_length=8, verbose_name='Categoria'),
        ),
    ]
