# Generated by Django 4.2.3 on 2023-07-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photography_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
