# Generated by Django 4.2.3 on 2023-07-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_photography_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
